Landing page, About and Contact
linea-it/dri pull request #1536
Opened 2024-07-24 02:02 UTC by jandsonrj

2024-08-07 20:01 UTC, gschwend requested changes
@jandsonrj retorna por favor a página de contato para a versão sem o formulário, vamos aguardar até ter o backend resolvido para enviar essa nova versão para o branch principal.

2024-08-07 21:52 UTC, jandsonrj commented
> @jandsonrj retorna por favor a página de contato para a versão sem o formulário, vamos aguardar até ter o backend resolvido para enviar essa nova versão para o branch principal.

Alterações realizadas com sucesso! Além disso, o ícone do Instagram foi adicionado ao banner, proporcionando mais uma opção de mídia social. Os links para 'Twitter' e 'YouTube' também foram atualizados para refletir as URLs atuais.

2024-08-12 21:34 UTC, gschwend approved these changes
testado em localhost

2024-08-13 14:33 UTC, glaubervila approved these changes

2024-08-13 14:33 UTC, merged