chang about description
linea-it/dri pull request #1564
Opened 2024-09-05 13:09 UTC by jandsonrj

2024-09-05 14:17 UTC, gschwend approved these changes

2024-09-05 14:17 UTC, gschwend commented on frontend/landing_page/src/pages/AboutUs/index.js
> +                <p>LIneA - Laboratório Interinstitucional de e-Astronomia - is a multi-user laboratory operated by a non-profit organization (LIneA Association) with financial support predominantly f
... "Get to Know LIneA"</a> (talk in Brazilian Portuguese) on our <a href="https: ...

2024-09-05 14:22 UTC, gschwend requested changes
@jandsonrj aproveita esse branch para omitir o link para a página TUTORIALS no header. Pode ser?

2024-09-06 15:07 UTC, jandsonrj commented
> @jandsonrj aproveita esse branch para omitir o link para a página TUTORIALS no header. Pode ser?

sim, já fiz

2024-09-06 17:57 UTC, glaubervila approved these changes

2024-09-06 18:02 UTC, merged